<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Table</title>
    <!-- Add the Bootstrap stylesheet -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<body>
<div>
    <p> INFO ABOUT CURRENT USER</p>
    <br>
    name ${user.name}
    <br>
    surname ${user.surname}
    <br>
    email ${user.email}
</div>
</body>